version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432

  server:
    image: node:alpine
    volumes:
      - ./server:/usr/app
    working_dir: /usr/app
    depends_on:
      - db
    command: sh -c "yarn && yarn start"
