version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

  migrations:
    image: node:alpine
    volumes:
      - ./services/database:/usr/app
    depends_on:
      - db

  server:
    image: node:alpine
    volumes:
      - ./services/server:/usr/app
    working_dir: /usr/app
    command: sh -c "yarn && yarn start"
    depends_on:
      - migrations

  discovery-service:
    image: node:alpine
    volumes:
      - ./services/discovery-service:/usr/app
    working_dir: /usr/app
    network_mode: host
    command: sh -c "yarn && yarn start"
    depends_on:
      - migrations
