version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${POSTGRES_ADMIN_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD}"

  migrations:
    image: node:alpine
    restart: on-failure
    volumes:
      - ./services/migrations:/usr/app/
      - /usr/app/node_modules/ # allow image to have it's own node_modules
      - /usr/app/build/ # allow image to have it's own build

    working_dir: /usr/app
    environment:
      - "ADMIN_USER=${POSTGRES_ADMIN_USER}"
      - "ADMIN_PASSWORD=${POSTGRES_ADMIN_PASSWORD}"
      - DATABASE_ADDRESS=db
      - DATABASE_PORT=5432
      - API_PORT=5442
      - DATABASE=postgres

    command: sh -c "yarn && yarn start"
    depends_on:
      - db

  server:
    image: node:alpine
    volumes:
      - ./services/server:/usr/app/
      - /usr/app/node_modules/ # allow image to have it's own node_modules
      - /usr/app/build/ # allow image to have it's own build

    working_dir: /usr/app
    ports:
      - "56700:56700/udp"
    command: sh -c "yarn && yarn start"
    depends_on:
      - db
