version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

  migrations:
    image: node:alpine
    restart: on-failure
    volumes:
      - ./services/database:/usr/app
    working_dir: /usr/app
    environment:
      - POSTGRES_USER=admin
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - DB_ADDRESS=db
      - DB_PORT=5432
    command: sh -c "yarn && yarn start"
    depends_on:
      - db

  server:
    image: node:alpine
    volumes:
      - ./services/server:/usr/app
    working_dir: /usr/app
    ports:
      - "56700:56700/udp"
    command: sh -c "yarn && yarn start"
    depends_on:
      - db
