version: "3.1"

services:
  db:
    image: postgres
    restart: always

  server:
    build: ./server
    ports:
      - "9229:9229"
    depends_on:
      - db
    command: yarn start:debug
