version: "3.1"

services:
  server:
    image: node:alpine
    environment:
      - DATABASE_URL=postgres://postgres@0.0.0.0/postgres
    volumes:
      - ./server:/usr/app
    working_dir: /usr/app
    command: sh -c "yarn && yarn start:watch"
