version: "3.1"

services:
  db:
    image: postgres
    restart: always

  server:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    build:
      context: ./server
    depends_on:
      - db
    command: yarn start
    # network_mode: host
