version: "3.1"

services:
  db:
    image: postgres
    restart: always

  server:
    image: node:alpine
    volumes:
      - ./services/server:/usr/app
    working_dir: /usr/app
    depends_on:
      - db
    command: sh -c "yarn && yarn start"
